/**
 * Valores reales reportados en la investigación (proyección a 90 días del
 * modelo Random Forest) y parámetros operativos de cada producto.
 *
 * factorExistencia: existenciaActual = ⌈puntoReorden × factor⌉. Valores ≤ 1
 * dejan el producto en estado crítico; entre 1 y 1.25, moderado; > 1.25, estable.
 */
export const CATALOGO = [
  {
    sku: 'CAF-001',
    nombre: 'CAFÉ',
    categoria: 'Bebidas calientes',
    total: 1128,
    min: 1,
    max: 25,
    nivelServicio: 0.95,
    leadTimeDias: 1,
    factorExistencia: 0.6,
    estacional: -0.12,
  },
  {
    sku: 'EMP-002',
    nombre: 'EMPANADA',
    categoria: 'Salados',
    total: 438,
    min: 0,
    max: 7,
    nivelServicio: 0.95,
    leadTimeDias: 2,
    factorExistencia: 0.75,
    estacional: 0,
  },
  {
    sku: 'KEK-003',
    nombre: 'KEKE',
    categoria: 'Pastelería',
    total: 311,
    min: 0,
    max: 5,
    nivelServicio: 0.9,
    leadTimeDias: 2,
    factorExistencia: 0.9,
    estacional: 0,
  },
  {
    sku: 'TAR-004',
    nombre: 'TARTALETA',
    categoria: 'Pastelería',
    total: 253,
    min: 0,
    max: 5,
    nivelServicio: 0.9,
    leadTimeDias: 2,
    factorExistencia: 1.15,
    estacional: 0,
  },
  {
    sku: 'INF-005',
    nombre: 'INFUSIÓN',
    categoria: 'Bebidas calientes',
    total: 208,
    min: 0,
    max: 5,
    nivelServicio: 0.9,
    leadTimeDias: 1,
    factorExistencia: 1.8,
    estacional: -0.2,
  },
  {
    sku: 'FRA-006',
    nombre: 'FRAPPÉ MEDIANO',
    categoria: 'Bebidas frías',
    total: 175,
    min: 0,
    max: 3,
    nivelServicio: 0.9,
    leadTimeDias: 1,
    factorExistencia: 1.6,
    estacional: 0.35,
  },
  {
    sku: 'GAS-007',
    nombre: 'GASEOSA',
    categoria: 'Bebidas frías',
    total: 175,
    min: 0,
    max: 4,
    nivelServicio: 0.9,
    leadTimeDias: 3,
    factorExistencia: 2.1,
    estacional: 0.25,
  },
  {
    sku: 'ENC-008',
    nombre: 'ENCHILADA',
    categoria: 'Salados',
    total: 158,
    min: 0,
    max: 3,
    nivelServicio: 0.9,
    leadTimeDias: 2,
    factorExistencia: 0.85,
    estacional: 0,
  },
  {
    sku: 'HAM-009',
    nombre: 'HAMBURGUESA',
    categoria: 'Salados',
    total: 129,
    min: 0,
    max: 3,
    nivelServicio: 0.9,
    leadTimeDias: 2,
    factorExistencia: 1.2,
    estacional: 0,
  },
  {
    sku: 'GAL-010',
    nombre: 'GALLETA',
    categoria: 'Pastelería',
    total: 101,
    min: 0,
    max: 3,
    nivelServicio: 0.9,
    leadTimeDias: 3,
    factorExistencia: 2.4,
    estacional: 0,
  },
];

export const HISTORIA_DESDE = '2024-01-03';
export const HISTORIA_HASTA = '2026-04-26';
export const PREDICCION_DESDE = '2026-04-27';
export const HORIZONTE = 90;
export const MODELO_VERSION = 'rf-v1.0';
